# Generated by Django 5.2.15 on 2026-07-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-briefcase', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_negotiable', models.BooleanField(default=False)),
                ('experience_required', models.CharField(help_text='e.g. 2-4 years', max_length=50)),
                ('qualification', models.CharField(max_length=150)),
                ('skills_required', models.TextField(help_text='Comma-separated skills e.g. Python, Django, React')),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('internship', 'Internship'), ('fresher', 'Fresher')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending_approval', 'Pending Approval'), ('flagged', 'Flagged as Fake')], default='active', max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seeker', 'job')},
            },
        ),
    ]
