# Generated by Django 5.2.15 on 2026-07-17 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisitorlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='sitevisitorlog',
            name='action_type',
            field=models.CharField(default='Page View', max_length=50),
        ),
        migrations.AddField(
            model_name='sitevisitorlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
